# The Docker image that will be used to build your app
image: alpine:latest

pages:
    stage: deploy
    script:
        - echo "No script needed"
    artifacts:
        paths:
            - public
    only:
        - master